# Generated by Django 3.0.8 on 2020-07-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200728_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('myImage', models.ImageField(upload_to='images/')),
                ('myResume', models.FileField(upload_to='images/')),
            ],
        ),
    ]
